# Generated by Django 2.0.8 on 2020-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20180530_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='batch',
            field=models.CharField(choices=[('morning', 'Male'), ('evening', 'Female')], default='morning', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=30, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_history',
            field=models.CharField(blank=True, default='None', max_length=300, verbose_name='Civil Record'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('gym', 'Basic'), ('cross_fit', 'Gold'), ('gym_and_cross_fit', 'Premium')], default='gym', max_length=30, verbose_name='Subscription Type'),
        ),
    ]
